name: test
on: [push]

jobs:
  generate-sha:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.generate-sha.outputs.matrix }}
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y git
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: zephyrproject-rtos/zephyr
        path: zephyr
        fetch-depth: 0
    - name: Generate matrix
      id: generate-sha
      run: |
        matrix=$(git -C zephyr log -n 1 --format='"%H",' | tr '\n' ' ')
        # Delete last character
        matrix="${matrix%?}"
        # Add [ ]
        matrix="[${matrix}]"
        echo "::set-output name=matrix::$matrix"
        echo "matrix: $matrix"
    - name: Upload load graphs
      uses: actions/upload-artifact@v2
      with:
        name: plots
        path: |
          **/plot_*.svg
  build:
    runs-on: ubuntu-20.04
    needs: [generate-sha]
    strategy:
      matrix:
        SHA: ${{ fromJson(needs.generate-sha.outputs.matrix) }}
      fail-fast:
        false
    env:
      ZEPHYR_SDK_VERSION: 0.14.2
      FORCE_BUILD: true
    steps:
    - uses: actions/checkout@v2
    - name: Prepare zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
      continue-on-error: true
    - name: Build boards
      run: ./scripts/build.py
      continue-on-error: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.SHA }}
        path: artifacts/*
  simulate:
    runs-on: ubuntu-20.04
    needs: [generate-sha, build]
    strategy:
      fail-fast: false
      matrix:
        SHA: ${{ fromJson(needs.generate-sha.outputs.matrix) }}
    env:
      RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.SHA }}
      continue-on-error: true
    - run: |
        ls -la
        ls -la artifacts
        tree artifacts
    - run: |
        ./scripts/download_renode.sh
      continue-on-error: true
    - run: |
        ./scripts/simulate.py
      continue-on-error: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.SHA }}
        path: |
          artifacts/*
  results:
    runs-on: ubuntu-20.04
    needs: [simulate]
    env:
      GHA_SA: "gh-sa-gcp-distributed-job-buck"
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        path: results
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y curl gnupg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt -qqy update && sudo apt -qqy install google-cloud-cli

    - run: |
        ls -la results
        cat results/*/*.txt
        cat results/*/*.txt > result.txt
        gsutil cp result.txt gs://gcp-distributed-job-test-bucket
    - name: Find artifacts that are no longer needed
      id: get-artifacts-to-delete
      run: |
        artifacts=$(find ./results -type d -name '*.txt' -exec basename {} \;)
        echo $artifacts
        artifacts="${artifacts//'%'/'%25'}"
        artifacts="${artifacts//$'\n'/'%0A'}"
        artifacts="${artifacts//$'\r'/'%0D'}"
        echo ::set-output name=artifacts::$artifacts
        echo $artifacts
    - name: Delete Old Artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: ${{ steps.get-artifacts-to-delete.outputs.artifacts }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: |
          **/result.txt
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: plots
        path: |
          **/plot_*.svg
