name: workflow
on: [push]

jobs:
  prepare-zephyr-6cfb18686e:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      ZEPHYR_SDK_VERSION: 0.14.2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Download Zephyr
      run: ./scripts/download_zephyr.sh
    - name: Pass Zephyr as artifact
      uses: actions/upload-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr.tar.gz
  prepare-zephyr-a41f4f30b5:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      ZEPHYR_SDK_VERSION: 0.14.2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Download Zephyr
      run: ./scripts/download_zephyr.sh
    - name: Pass Zephyr as artifact
      uses: actions/upload-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr.tar.gz
  build-6cfb18686e-hello_world:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-6cfb18686e]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      SAMPLE_NAME: hello_world
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  simulate-6cfb18686e-hello_world:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-6cfb18686e-hello_world]
    env:
       SAMPLE_NAME: hello_world
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  build-6cfb18686e-shell_module:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-6cfb18686e]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      SAMPLE_NAME: shell_module
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  simulate-6cfb18686e-shell_module:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-6cfb18686e-shell_module]
    env:
       SAMPLE_NAME: shell_module
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  build-6cfb18686e-philosophers:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-6cfb18686e]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      SAMPLE_NAME: philosophers
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  simulate-6cfb18686e-philosophers:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-6cfb18686e-philosophers]
    env:
       SAMPLE_NAME: philosophers
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  build-6cfb18686e-micropython:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-6cfb18686e]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      SAMPLE_NAME: micropython
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  simulate-6cfb18686e-micropython:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-6cfb18686e-micropython]
    env:
       SAMPLE_NAME: micropython
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  build-6cfb18686e-tensorflow_lite_micro:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-6cfb18686e]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      SAMPLE_NAME: tensorflow_lite_micro
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  simulate-6cfb18686e-tensorflow_lite_micro:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-6cfb18686e-tensorflow_lite_micro]
    env:
       SAMPLE_NAME: tensorflow_lite_micro
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 6cfb18686e
        path: artifacts/
  build-a41f4f30b5-hello_world:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-a41f4f30b5]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      SAMPLE_NAME: hello_world
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  simulate-a41f4f30b5-hello_world:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-a41f4f30b5-hello_world]
    env:
       SAMPLE_NAME: hello_world
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  build-a41f4f30b5-shell_module:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-a41f4f30b5]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      SAMPLE_NAME: shell_module
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  simulate-a41f4f30b5-shell_module:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-a41f4f30b5-shell_module]
    env:
       SAMPLE_NAME: shell_module
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  build-a41f4f30b5-philosophers:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-a41f4f30b5]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      SAMPLE_NAME: philosophers
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  simulate-a41f4f30b5-philosophers:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-a41f4f30b5-philosophers]
    env:
       SAMPLE_NAME: philosophers
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  build-a41f4f30b5-micropython:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-a41f4f30b5]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      SAMPLE_NAME: micropython
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  simulate-a41f4f30b5-micropython:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-a41f4f30b5-micropython]
    env:
       SAMPLE_NAME: micropython
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  build-a41f4f30b5-tensorflow_lite_micro:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [prepare-zephyr-a41f4f30b5]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      SAMPLE_NAME: tensorflow_lite_micro
      MICROPYTHON_VERSION: 97a7cc243b
      NUMBER_OF_THREADS: 2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Prepare Micropython
      run: ./scripts/prepare_micropython.sh
    - name: Build boards
      run: ./scripts/build.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  simulate-a41f4f30b5-tensorflow_lite_micro:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [build-a41f4f30b5-tensorflow_lite_micro]
    env:
       SAMPLE_NAME: tensorflow_lite_micro
       RENODE_VERSION: 1.13.1+20220731git8eca7310
    steps:
    - uses: actions/checkout@v2
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Prepare Renode
      run: ./scripts/download_renode.sh
    - name: Add renode to PATH
      run: export PATH=$PATH:`pwd`/renode_portable
    - name: Simulate
      run: ./scripts/simulate.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: a41f4f30b5
        path: artifacts/
  results:
    container: ubuntu:focal
    runs-on: [self-hosted, Linux, X64]
    needs: [simulate-6cfb18686e-hello_world, simulate-6cfb18686e-shell_module, simulate-6cfb18686e-philosophers, simulate-6cfb18686e-micropython, simulate-6cfb18686e-tensorflow_lite_micro, simulate-a41f4f30b5-hello_world, simulate-a41f4f30b5-shell_module, simulate-a41f4f30b5-philosophers, simulate-a41f4f30b5-micropython, simulate-a41f4f30b5-tensorflow_lite_micro]
    steps:
    - name: Delete unnecessary artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: |
          zephyr-6cfb18686e
          zephyr-a41f4f30b5
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        path: results/
    - name: Install dependencies
      run: |
        apt update -qq
        apt install -y curl gnupg
    - name: Delete unnecessary artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: |
          6cfb18686e
          a41f4f30b5
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: results