name: workflow
on: [push]

jobs:
  prepare-zephyr-62f19cc6b3:
    runs-on: ubuntu-20.04
    env:
      ZEPHYR_COMMIT: 62f19cc6b3
    steps:
    - name: Download Zephyr
      run: echo "Download Zephyr"
    - name: Tar Zephyr
      run: echo "Tar Zephyr"
    - name: Pass Zephyr as artifact
      run: echo "Pass Zephyr as artifact"
  prepare-zephyr-f72eb8d40d:
    runs-on: ubuntu-20.04
    env:
      ZEPHYR_COMMIT: f72eb8d40d
    steps:
    - name: Download Zephyr
      run: echo "Download Zephyr"
    - name: Tar Zephyr
      run: echo "Tar Zephyr"
    - name: Pass Zephyr as artifact
      run: echo "Pass Zephyr as artifact"
  build-62f19cc6b3-hello_world:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-62f19cc6b3]
    env:
      ZEPHYR_COMMIT: 62f19cc6b3
      SAMPLE_NAME: hello_world
    steps:
    - name: Get Zephyr
      run: echo "Get Zephyr"
    - name: Test
      run: echo $SAMPLE_NAME
  simulate-62f19cc6b3-hello_world:
    runs-on: ubuntu-20.04
    needs: [build-62f19cc6b3-hello_world]
    env:
       SAMPLE_NAME: hello_world
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  build-62f19cc6b3-shell_module:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-62f19cc6b3]
    env:
      ZEPHYR_COMMIT: 62f19cc6b3
      SAMPLE_NAME: shell_module
    steps:
    - name: Get Zephyr
      run: echo "Get Zephyr"
    - name: Test
      run: echo $SAMPLE_NAME
  simulate-62f19cc6b3-shell_module:
    runs-on: ubuntu-20.04
    needs: [build-62f19cc6b3-shell_module]
    env:
       SAMPLE_NAME: shell_module
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  build-f72eb8d40d-hello_world:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-f72eb8d40d]
    env:
      ZEPHYR_COMMIT: f72eb8d40d
      SAMPLE_NAME: hello_world
    steps:
    - name: Get Zephyr
      run: echo "Get Zephyr"
    - name: Test
      run: echo $SAMPLE_NAME
  simulate-f72eb8d40d-hello_world:
    runs-on: ubuntu-20.04
    needs: [build-f72eb8d40d-hello_world]
    env:
       SAMPLE_NAME: hello_world
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  build-f72eb8d40d-shell_module:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-f72eb8d40d]
    env:
      ZEPHYR_COMMIT: f72eb8d40d
      SAMPLE_NAME: shell_module
    steps:
    - name: Get Zephyr
      run: echo "Get Zephyr"
    - name: Test
      run: echo $SAMPLE_NAME
  simulate-f72eb8d40d-shell_module:
    runs-on: ubuntu-20.04
    needs: [build-f72eb8d40d-shell_module]
    env:
       SAMPLE_NAME: shell_module
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  results:
    runs-on: ubuntu-20.04
    needs: [simulate-62f19cc6b3-hello_world, simulate-62f19cc6b3-shell_module, simulate-f72eb8d40d-hello_world, simulate-f72eb8d40d-shell_module]
    steps:
    - name: Test results
      run: echo "Working!!"