name: workflow2
on:
  push:
    paths-ignore:
      - 'last_zephyr_commit'
jobs:
  prepare-zephyr-0:
    container: ubuntu:jammy
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2
      - name: Set out var
        id: set_out_var
        run: echo "::set-output name=ZEPHYR_COMMIT::$(cat last_zephyr_commit)"
      - name: Get out var
        run: echo ${{ steps.set_out_var.outputs.ZEPHYR_COMMIT }}
