name: workflow
on: [push]

jobs:
  prepare-zephyr-6cfb18686e:
    runs-on: ubuntu-20.04
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      ZEPHYR_SDK_VERSION: 0.14.2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Download Zephyr
      run: ./scripts/download_zephyr.sh
    - name: Pass Zephyr as artifact
      uses: actions/upload-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr.tar
  prepare-zephyr-a41f4f30b5:
    runs-on: ubuntu-20.04
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      ZEPHYR_SDK_VERSION: 0.14.2
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: ./scripts/prepare_environment.sh
    - name: Download Zephyr
      run: ./scripts/download_zephyr.sh
    - name: Pass Zephyr as artifact
      uses: actions/upload-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr.tar
  build-6cfb18686e-hello_world:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-6cfb18686e]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      SAMPLE_NAME: hello_world
    steps:
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Test
      run: ls -la
  simulate-6cfb18686e-hello_world:
    runs-on: ubuntu-20.04
    needs: [build-6cfb18686e-hello_world]
    env:
       SAMPLE_NAME: hello_world
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  build-6cfb18686e-shell_module:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-6cfb18686e]
    env:
      ZEPHYR_COMMIT: 6cfb18686e
      SAMPLE_NAME: shell_module
    steps:
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-6cfb18686e
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Test
      run: ls -la
  simulate-6cfb18686e-shell_module:
    runs-on: ubuntu-20.04
    needs: [build-6cfb18686e-shell_module]
    env:
       SAMPLE_NAME: shell_module
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  build-a41f4f30b5-hello_world:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-a41f4f30b5]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      SAMPLE_NAME: hello_world
    steps:
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Test
      run: ls -la
  simulate-a41f4f30b5-hello_world:
    runs-on: ubuntu-20.04
    needs: [build-a41f4f30b5-hello_world]
    env:
       SAMPLE_NAME: hello_world
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  build-a41f4f30b5-shell_module:
    runs-on: ubuntu-20.04
    needs: [prepare-zephyr-a41f4f30b5]
    env:
      ZEPHYR_COMMIT: a41f4f30b5
      SAMPLE_NAME: shell_module
    steps:
    - name: Get Zephyr
      uses: actions/download-artifact@v2
      with:
        name: zephyr-a41f4f30b5
        path: zephyr-artifact
    - name: Prepare Zephyr
      run: ./scripts/prepare_zephyr.sh
    - name: Test
      run: ls -la
  simulate-a41f4f30b5-shell_module:
    runs-on: ubuntu-20.04
    needs: [build-a41f4f30b5-shell_module]
    env:
       SAMPLE_NAME: shell_module
    steps:
    - name: Test simulate
      run: echo $SAMPLE_NAME
  results:
    runs-on: ubuntu-20.04
    needs: [simulate-6cfb18686e-hello_world, simulate-6cfb18686e-shell_module, simulate-a41f4f30b5-hello_world, simulate-a41f4f30b5-shell_module]
    steps:
    - name: Test results
      run: echo "Working!!"